---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

#
- name: Copy EAR
  copy: remote_src=True
        src={{ ansible_env.HOME }}/ipst_ansible/ipst/iidm-ddb/iidm-ddb-ear/target/iidm-ddb-ear.ear
        dest=$JBOSS_HOME/standalone/deployments/iidm-ddb-ear.ear
  become: true
  become_user: root

# minimal test data
- name: extract minimalist DDB
  unarchive: src="~/minimalist_DDB.zip"
             dest="{{ ansible_env.HOME }}"
             creates="{{ ansible_env.HOME }}/minimalist_DDB"
  register: hadesInstalled


#
- name: remove archive
  file: state=absent path={{ ansible_env.HOME }}/minimalist_DDB.zip

#
# service mysqld start
# service mysqld stop
# service mysqld restart
- name: Start dbmaria Service
  become: true
  become_user: root
  command: sudo service mysqld start
  register: dbmaria_start
  ignore_errors: yes

#
- name: Report start of mysql
  fail:
    msg: |
      Service mysql is not running.
      {{ dbmaria_start.stdout }}
      {{ dbmaria_start.stderr }}
  when: dbmaria_start | failed

- name: Create init db script
  template: src=init_dbmaria.j2
            dest="{{ ansible_env.HOME }}/init_dbmaria.sql"


#
- name: Initialize DB
  shell: mysql < init_dbmaria.sql
  register: dbmaria_init
  become: true
  become_user: root

#
- name: remove init db script
  file: state=absent
        path={{ ansible_env.HOME }}/init_dbmaria.sql

#
- name: wildFly start service
  service: name=wildfly enabled=yes state=started
  become: true
  become_user: root
  register: wildfly_start
  ignore_errors: yes

#
- name: wildfly log
  command: cat /var/log/wildfly/console.log
  register: wildfly_start_cat

#
- name: Report start of Wildfly
  fail:
    msg: |
      Service wildfly is not running.
      {{ wildfly_start.stdout }}
      {{ wildfly_start.stderr }}
  when: wildfly_start | failed

#
- name: test
  become: true
  become_user: root
  shell: "netstat -lntup"
  register: netstatB

#
- name: unload previous data
  command: "{{ipst_install_path}}/bin/itools ddb-unload --host 127.0.0.1 --port 8080 --user user --password password"
  register: ddb_unload

#
- name: load new data
  command: "{{ipst_install_path}}/bin/itools ddb-load-eurostag --host 127.0.0.1 --port 8080 --user user --password password --eurostag-version 5.1.1 --data-dir {{ ansible_env.HOME }}/minimalist_DDB"
  register: ddb_load
  #in case, ignore errors (to proceed to next steps and possibly log the errors)
  ignore_errors: True


#
- debug:
    var="{{ item }}"
  when: "1==0"
  with_items:
      - test_analysis
      - wildfly_start
      - wildfly_start_cat
      - dbmaria_start
      - dbmaria_init
      - ddb_unload.stdout_lines
      - ddb_load.stdout_lines
      - netstatB.stdout_lines

#local dumps a per-host log of iPST install script execution
- name: load dump log, to
  local_action: copy content="cmd=> {{ ddb_load.cmd }}\nstart=> {{ ddb_load.start }}\nend=> {{ ddb_load.end }}\n===== DUMP OUT =====\n{{ ddb_load.stdout }}\n===== DUMP ERR =====\n{{ ddb_load.stderr }}"
                dest="~/{{ inventory_hostname }}_tmp"
  when: ddb_load is defined

# format log file
- name: load format log
  local_action: shell /usr/bin/sed 's/\\n/\n/g' <~/{{ inventory_hostname }}_tmp >{{ playbook_dir }}/install_ddb_{{ inventory_hostname }}.log && rm ~/{{ inventory_hostname }}_tmp
  when: ddb_load is defined

#
- name: check load data
  fail:
    msg: |
      Loading test data fail
      please check install_ddb_XXX.log file
  when: '" ERROR " in ddb_load.stdout'
