---

#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# 

###
###
# This ansible playbook builds and installs IPST on a target CentOS linux (tested versions 6.5, 7.0, 7.2). In particular:
# 
# A) it installs on the target server all the OS packages and SW runtimes, needed to build and run the platform
#     -C/C++development tools (gcc, g++, make, git, etc)
#     -CMake
#     -OpenMPI (sources installation + local build with flag --enable-mpi-thread-multiple)
#     -Oracle JDK8 
#     -Apache Maven
#     -MATLAB Runtime (MCR)
#
#  Notes:
#      1) admin rights are required to install all the above mentioned packages and runtimes
#      2) in case all the packages are already available on the target OS, this step can be skipped ( set variable installPrerequisites to be False, in the inventory ipst-hosts file)
#
# B) on the target server(s): it clones the IPST project sources from GitHub (or pull onto an existing repository), builds the  'platform distribution' and installs it
#
#

##
# the target hosts
- hosts: all

###
###
# environment variables at this playbook level
  environment: "{{ ipst_environment | default('{}') }}"

###
###
  vars:

# if set, clone/updates the ipst repository on target OS from github
    ipst_github_enabled: "{{ github_enabled|default('True') }}"

# if set to False, do not try installing all the prerequisite packages: common development tools, openmpi libraries, jdk, maven;
#  useful if already available on the target OS and no admin rights are available
    installPrerequisites: "{{ install_prerequisites|default('True') }}"

# if set to False, do not try installing the matlab runtime;
#  useful if already available on the target OS and no admin rights are available
    installMCR: "{{ install_MCR|default('False') }}"
    
# if set to True, always triggers the ipst platfrom build, even if there are no updates from github
    forceBuild: "{{ force_build|default('True') }}"

# path on target OS where ipst sources will be cloned/updated
    ipst_sources_path_default: "{{  ansible_env.HOME }}/ipst_ansible/ipst"
    ipst_sources_path: "{{ sources_path|default(ipst_sources_path_default) }}"

# path on target OS where ipst thirdparty libraries will be installed
    ipst_thirdparty_path_default: "{{  ansible_env.HOME }}/ipst_ansible/thirdparty"
    ipst_thirdparty_path: "{{ thirdparty_path | default(ipst_thirdparty_path_default) }}"

# path on target OS where ipst will be installed
    ipst_install_path_default: "{{  ansible_env.HOME }}/itesla"
    ipst_install_path: "{{ install_path|default(ipst_install_path_default) }}"

# path on local OS, source of additional thirdparty libraries to be installed (as-is: untgz to ipst_install_path)
    misc_thirdparties_path: "./misc"

# ipst github project details
## TODO branchname must be set to master, eventually
    ipst_github_branchname: "{{ github_branchname|default('ansible2') }}"

# ipst_thirdparty_packs
    ipst_thirdparty_packs_path_default: "{{  ansible_env.HOME }}/ipst_ansible/thirdparty_packs"
    ipst_thirdparty_packs_path: "{{  thirdparty_packs|default(ipst_thirdparty_packs_path_default) }}"

###
###
### dump variable's content

  pre_tasks:
  - debug: var="installPrerequisites"
  - debug: var="installMCR"
  - debug: var="ipst_github_enabled"
  - debug: var="ipst_github_branchname"
  - debug: var="ipst_sources_path"
  - debug: var="ipst_install_path"
  - debug: var="ipst_thirdparty_path"

###
###
###

  roles:
    - { role: ipst.common, when: "installPrerequisites == True", become: "yes" }
    - { role: ipst.openmpi, when: "installPrerequisites == True", become: "yes" }
    - { role: ipst.jdk8, when: "installPrerequisites == True", become: "yes" }
    - { role: ipst.maven, when: "installPrerequisites == True", become: "yes" }
    - { role: ipst.mcr, when: "installMCR == True", become: "yes" }
    - { role: ipst.ipst }
