---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

- name: Create maven home folder
  file: state=directory path="{{ maven_home }}"
  register: maven_create_folder_log
#- debug: var="maven_create_folder_log"

# install tasks file for ipst.maven
- name: Download maven
  get_url: url={{ maven_url }} dest=/tmp/{{ maven_bin_filename }}
  register: download
- debug: var="download"

- name: extract maven
  #unarchive: copy=no src="/tmp/{{ maven_bin_filename }}" dest="{{ maven_dest_path }}" creates="{{ maven_home }}"
  unarchive: copy=no src="/tmp/{{ maven_bin_filename }}" dest="{{ maven_dest_path }}"
  register: maveninstalled

#manage via alternative
#- name: Make Maven available for system
#command: 'alternatives --install "/usr/bin/mvn" "mvn" "{{ maven_dest_path }}/bin/mvn" 999999'

- name: Clean up
  file: state=absent path="/tmp/{{ maven_bin_filename }}"

#- name: add environment variables config file
#  when: maveninstalled|success
#  register: maven_envvars_config
#  template: src=maven_env.sh.j2 dest="/etc/profile.d/maven_env.sh" owner=root group=root

# define env variables
- name: Update bashrc file
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "## {mark} maven"
    block: |
      export MAVEN_HOME="{{ maven_home }}"
      export PATH=$MAVEN_HOME/bin:$PATH
    create: yes


