---
# defaults file for ipst.maven

# maven prefix install path, default is project_home/maven when user_maven_dest_path is undefined
maven_dest_path: "{{ project_home + '/' + user_maven_dest_path |default('maven') }}"

# maven install version, default is 3.0.5 when user_maven_version is undefined
maven_version: "{{ user_maven_version |default('3.0.5') }}"

#maven_mirror: "https://www.apache.org/dist/maven/maven-3/3.3.9/binaries"
# maven install mirror, default is http://archive.apache.org/dist/maven/binaries when user_maven_mirror is undefined
maven_mirror: "{{ user_maven_mirror |default('http://archive.apache.org/dist/maven/binaries') }}"

# maven full install path
maven_home: "{{ maven_dest_path +'/apache-maven-'+ maven_version }}"

# maven archive name
maven_bin_filename: "apache-maven-{{ maven_version }}-bin.tar.gz"

# maven full archive mirror
maven_url: "{{ maven_mirror }}/{{ maven_bin_filename  }}"

## et donc avec ${env.ftp_proxy} plus besoin de mettre les proxies
maven_proxies: "{{ user_maven_proxies |default([]) }}"

#{{ user_maven_repository | regex_replace('[$]HOME', '${env.HOME}')  }}
#maven_repository_tmp: "{{ user_maven_repository| default('$HOME/.m2/repository') }}"

maven_repository: "{{ user_maven_repository| default('$HOME/.m2/repository') }}"
maven_repository_settings: "{{ maven_repository | regex_replace('[$]HOME', '${env.HOME}')  }}"