---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#


# main tasks file for ipst.mariadb

- debug: var="mariadb_log_file"

# check
- name: check if already installed
  stat: path={{ mariadb_home }}
  register: mariadb_dir
  changed_when: mariadb_dir.stat.exists == False

# log some variables
- debug:
    var="{{ item }}"
  with_items:
    - mariadb_url
    - mariadb_home
    - mariadb_conf
    - mariadb_log_file


- include: install.yml
  when: mariadb_dir.stat.exists == False