---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# 

# clone/update ipst-core from github
  - include: install_core.yml

# clone/update ipst-entsoe from github
  - include: install_entsoe.yml

# clone/update ipst from github
  - include: install_ipst.yml
