---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# 
# to load mpi path  
  - name: source bashrc file
    shell: source {{ ansible_env.HOME }}/.bashrc
# clone/update powsybl-core from github
  - include: install_core.yml

# clone/update ipst-cgmes from github
  - include: install_cgmes.yml
    when: user_cgmes_enabled == True
   
# clone/update ipst from github
  - include: install_ipst.yml
    when: user_ipst_enabled == True
  
  - name: Update bashrc file
    blockinfile:
        dest: "{{ ansible_env.HOME }}/.bashrc"
        marker: "## {mark} itools"
        block: |
            export PATH={{ipst_install_path}}/bin:$PATH        
        create: yes
