---
#
# Copyright (c) 2016, RTE (http://www.rte-france.com)
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#


# install tasks file for ipst.wildfly

#
- name: wildfly download
  command: "wget -q -O /tmp/{{ wildfly_archivename }} --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' {{ wildfly_url }}"

# create the wildfly home directory if not exist
- name: create home folder
  file: state=directory path="{{ wildfly_prefix }}"
  register: wildfly_create_folder_log

#
- name: wildfly extract
  unarchive:
      copy: no
      src: "/tmp/{{ wildfly_archivename }}"
      dest: "{{ project_home }}"
  ignore_errors: True
  register: wildflyinstalled

# define env variables
- name: Update bashrc file
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bashrc"
    marker: "## {mark} wildfly"
    block: |
      export JBOSS_HOME={{ wildfly_prefix }}
      export PATH=$JBOSS_HOME/bin:$PATH
    create: yes

#
#- name: add environment variables config file
#  when: wildflyinstalled|success
#  register: wildfly_envvars_config
#  template: src=wildfly_env.sh.j2 dest="/etc/profile.d/wildfly_env.sh"
#   #owner=root group=root
#  #become: False

#
#- name: Fix ownership
#  file: state=directory path={{ wildfly_prefix }} owner=root group=root recurse=yes

#
- name: create mysql connector directory
  file: path="{{ wildfly_prefix }}/modules/com/mysql/main"
        state=directory

#
- name: download mysql connector
  command: "wget -q -O /tmp/mysql-connector-java-5.1.23-bin.jar.zip --no-check-certificate --no-cookies --header 'Cookie: oraclelicense=accept-securebackup-cookie' http://www.java2s.com/Code/JarDownload/mysql/mysql-connector-java-5.1.23-bin.jar.zip"
  when: wildflyinstalled|success
  register: res

#
- name: connector extract
  unarchive: copy=no src="/tmp/mysql-connector-java-5.1.23-bin.jar.zip" dest="{{ wildfly_prefix }}/modules/com/mysql/main" creates="{{ wildfly_prefix }}/modules/com/mysql/main/mysql-connector-java-5.1.23-bin.jar"
  register: wildflyinstalled

#
- name: add mysql connector config
  when: wildflyinstalled|success
  register: wildfly_module
  template: src=connector.j2 dest="{{ wildfly_prefix }}/modules/com/mysql/main/module.xml"

#
- name: add standalone to standalone
  when: wildflyinstalled|success
  register: wildfly_standalone
  template: src=standalone.j2 dest="{{ wildfly_prefix }}/standalone/configuration/standalone.xml"

#
- name: add module2
  when: wildflyinstalled|success
  register: wildfly_standalone
  template: src=module.j2 dest="{{ wildfly_prefix }}/modules/system/layers/base/sun/jdk/main/module.xml"


# add application user
- name: add application user
  shell: "{{ wildfly_prefix }}/bin/add-user.sh --silent -e -a -u user -g user -p password"
  args:
    executable: /bin/bash
  register: res


# add Management user
- name: add Management user
  shell: "{{ wildfly_prefix }}/bin/add-user.sh --silent -e -u admin -g admin -p password"
  args:
    executable: /bin/bash
  register: res

# install wildfly as service
#- name: Copy the init script
#  copy:
#    remote_src: True
#    src: $JBOSS_HOME/bin/init.d/wildfly-init-redhat.sh
#    dest: /etc/init.d/wildfly
#    mode: 0755
#  become: true
#  become_user: root
#- name: Copy wildfly conf
#  become: true
#  become_user: root
#  template: src=wildfly.conf.j2
#            dest="/etc/default/wildfly.conf"


#
- name: remove tmp
  file: state=absent path="/tmp/{{ wildfly_archivename }}"
- name: remove tmp
  file: state=absent path=/tmp/mysql-connector-java-5.1.23-bin.jar.zip

